# Generated by Django 4.1 on 2022-09-19 14:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateModified', models.DateTimeField(auto_now=True)),
                ('primaryKey', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('csv', models.FileField(upload_to='general/files/')),
                ('json', models.CharField(default='CandleJSONServiceProvider', max_length=32)),
                ('idl', models.CharField(default='CandleIDServiceProvider', max_length=32)),
                ('time', models.CharField(default='CandleTimeServiceProvider', max_length=32)),
                ('openl', models.CharField(default='CandleOpenServiceProvider', max_length=32)),
                ('close', models.CharField(default='CandleCloseServiceProvider', max_length=32)),
                ('high', models.CharField(default='CandleHighServiceProvider', max_length=32)),
                ('date', models.CharField(default='CandleDateServiceProvider', max_length=32)),
            ],
        ),
    ]
