# Generated by Django 4.1 on 2022-09-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='date',
            field=models.CharField(default='CandleDateerviceProvider', max_length=32),
        ),
    ]
