# Generated by Django 4.1 on 2022-09-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_alter_candle_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='volume',
            field=models.CharField(default='CandleVolumeServiceProvider', max_length=32),
        ),
    ]
