# Generated by Django 4.1 on 2022-09-27 11:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_candle_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
