# Generated by Django 4.1 on 2022-09-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_blog_delete_candle'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='readTime',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
