# Generated by Django 4.1 on 2022-09-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_alter_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(default='BlogTitleProvider', max_length=512),
        ),
    ]
